openapi: 3.0.0
info:
  title: TMDb API
  version: 1.0.0
  description: This is a simple API for accessing TMDb data including movie and TV series details.
servers:
  - url: 'https://api.themoviedb.org/3'
    description: Main API server
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: api_key
security:
  - ApiKeyAuth: []
paths:
  /discover/movie:
    get:
      summary: Get a list of movies sorted by popularity and rating
      parameters:
        - in: query
          name: sort_by
          schema:
            type: string
            default: popularity.desc,vote_average.desc
          description: Sort by criteria
      responses:
        '200':
          description: A list of movies
  /discover/tv:
    get:
      summary: Get a list of TV series sorted by popularity and rating
      parameters:
        - in: query
          name: sort_by
          schema:
            type: string
            default: popularity.desc,vote_average.desc
          description: Sort by criteria
      responses:
        '200':
          description: A list of TV series
  /movie/{movie_id}:
    get:
      summary: Access detailed information about a specific movie
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
          description: The ID of the movie
      responses:
        '200':
          description: Detailed movie information
  /tv/{tv_id}:
    get:
      summary: Access detailed information about a specific TV series
      parameters:
        - in: path
          name: tv_id
          required: true
          schema:
            type: integer
          description: The ID of the TV series
      responses:
        '200':
          description: Detailed TV series information
  /search/tv:
    get:
      summary: Search TV series by name
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
          description: The name of the TV series to search for
      responses:
        '200':
          description: Search results for TV series
